// swift-tools-version:5.9
// Generated by SwiftFlowKit

import PackageDescription

let package = Package(
    name: "iGetGroceriesSharedUI",
    platforms: [
        .iOS(.v17)
    ],
    products: [
        .library(
            name: "iGetGroceriesSharedUI",
//            type: .dynamic,
            targets: ["iGetGroceriesSharedUI"]),
    ],
    dependencies: [
        .package(url: "https://github.com/nikolainobadi/NnSwiftUIKit", from: "1.0.0")
    ],
    targets: [
        .target(
            name: "iGetGroceriesSharedUI",
            dependencies: [
                "NnSwiftUIKit"
            ],
            resources: [
                .process("Resources/SharedUI.xcassets")
            ]
        ),
    ]
)
